### ISSUE TITLE
Relearn save/load preset not working

### ISSUE THREAD

**Issue by kunsin** [helgoboss/helgobox#1172]
**Describe the bug**
In the recent version of Realearn, I've encountered a strange issue.

After mapping a set of plugin settings and saving the preset, when I reopen REAPER, the previously configured items in the preset become grayed out and unusable, whether I load it manually or automatically. It only works again after clicking "Learn Target" and reassigning the corresponding knobs.

The operating system is Windows 10, and I'm using a MIDI Fighter Twister as the controller. I've tried completely resetting and reinstalling Realearn 2, but the issue persists.

**To Reproduce**
1. Open Reaper
2. Open FX -> bx_SSL 9000J
3. Go to Realearn
4. Click on Learn Multi
5. Set Source and Target
6. Save Preset to Relearn
7. Close Reaper
8. Re-Open Reaper
9. Open FX -> bx_SSL 9000J
10. Go to Realearn
11. Load Preset
12. See error, preset not work

**Expected behavior**
After save/load preset, Realearn could works.

**Screenshots**

![image](https://github.com/user-attachments/assets/a9da2941-891b-44d5-b3ca-58525e991015)
![image](https://github.com/user-attachments/assets/a01c6cee-4461-41fa-aa18-3ca2b4ebde7c)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Reaper 7.22

**Comment by helgoboss** [comment]
When you saved the preset, ReaLearn must have shown you a message in which it recommends to make your mappings project-independent. My guess is that you just ignored this message instead of following the recommendation?

This has changed a bit in the last version. In previous versions, there was also a warning message, but if you pressed OK, it would automatically make the mappings project-independent. Maybe you were used to that. I removed this automatism so that the user can make a more conscious decision about how exactly modifying the mappings in order to make them project-independent.

Please watch ReaLearn video tutorial 9/10 to see how it works.

**Comment by kunsin** [comment]
Thanks and Sorry for I has skipped the message,  all them works fine now.
