### ISSUE TITLE
Rounding Bug #1

### ISSUE THREAD

**Issue by JackOrez** [helgoboss/helgobox#1214]
Bug #3:
https://stash.reaper.fm/v/49281/Keyboard_as_source.png

Rounding Error:
1) Learn a computer keyboard key as source.
2) Set target as OSC[Float], Range: 0.0 - 100.0, Value Sequence: 0.0 - 100.0 (0.30)
3) Set glue to 'Incremental button'
5) Create ReaScript like that in the attached pic. Close the script IDE.
4) Start pressing the key and at 16.2 you should notice the rounding error creeping in.

[https://stash.reaper.fm/49282/Endles...s_source-1.png](https://stash.reaper.fm/49282/Endless_knob_as_source-1.png)

Attached Endless_knob_as_source-1.png shows same error just a different setup.
1) Source is endless knob.
2) Target is same as previous example, except no 'Value Sequence' and glue mode is 'Make relative'

I assume this is happening because Helgobox is set internally to 14-bit resolution [16383], however awhile back
the devs added the 'contextstr' return variable which in the attached pic I have labeled 'osc'.

Maybe you could add ability to handle values beyond 16383?

Here is what the documentation says.[This was copied from the ultraschall_api doc 'Reaper_Api_Documentation.html' because it has better info]
------------------------------------------------------------------
get_action_context:

Lua: boolean is_new_value, string filename_with_path, integer sectionID, integer cmdID, integer mode, integer resolution, integer val, string contextstr = reaper.get_action_context()

Returns contextual information about the script, typically MIDI/OSC input values.val will be set to a relative or absolute value depending on mode (=0: absolute mode, >0: relative modes). resolution=127 for 7-bit resolution, =16383 for 14-bit resolution.Notes: sectionID, and cmdID will be set to -1 if the script is not part of the action list. mode, resolution and val will be set to -1 if the script was not triggered via MIDI/OSC.

For relative mode bindings, calling get_action_context() will return the accumulated relative value in decoded form (not 65 or 63, but +1/-1 etc), and clear the internal state. So if you call it multiple times, the first one will return the accumulated value, and the second will always return 0.

contextstr may be empty or one of:
midi:XX[:YY] (one or two bytes hex)
[wheel|hwheel|mtvert|mthorz|mtzoom|mtrot|mediakbd]:flags
key:flags:keycode
osc:/msg[:f=FloatValue|:s=StringValue]
KBD_OnMainActionEx
(flags may include V=virtkey, S=shift, A=alt/option, C=control/command, W=win/control)

Returnvalues:
boolean is_new_value:
unknown
string filename_with_path:
the script's own filename with path
integer sectionID:
the section, in which this script was called
integer cmdID:
the command-id associated with this script
integer mode:
-1, if script isn't run by shortcut; 55953, if script is run by shortcut
integer resolution:
-1, if script isn't run by shortcut; resolution of OSC(14 bit)/MIDI(7 bit)-shortcut
integer val:
-1, if script isn't run by shortcut; the value sent by OSC or MIDI
string contextstr:
the shortcut, that ran this action, more info in the description

**Comment by helgoboss** [comment]
Hmm. ReaLearn is not limited to 14-bit internally. It uses 64-bit floating pointer numbers in most places. Only when using target "Project: Invoke REAPER action", it uses 14-bit or 7-bit integers to invoke the action. But you are using the OSC target, so this doesn't apply. The OSC target internally maintains a 64-bit floating pointer to simulate a "current value". I say "simulate" because a OSC target doesn't inherently have a "current value" (unlike e.g. a track volume target). It's a convenience feature.

I will have a look at this specific issue at some point but it could be that it's not a bug. You are dealing with floating point values here, so rounding issues are something you need to live with to some degree. The OSC receiver should expect such things and do some rounding itself if it wants numbers to be integers.

Another way would be to define a compartment parameter in ReaLearn with a "value count". That will make the parameter become discrete, so rounding errors can't happen. You would then control that parameter. Then you have a 2nd mapping that uses this parameter as source and the OSC target, using absolute control ("Normal" mode in Glue section). This is an explicit way of simulating a "current value".

**Comment by helgoboss** [comment]
Okay, I had a closer look. As I thought, this is not a bug. Rounding errors like this creeping in after a while when doing transformations on high-precision floating point numbers are normal. If you choose OSC type "Double" (which exposes ReaLearn's generated numbers as-is in 64-bit), you will see this type of error much earlier (e.g. 0.000000000000000004) because there's no rounding to 32-bit Floats.

For discrete targets (targets whose value range has discrete steps, e.g. a list of tracks), ReaLearn automatically snaps to the correct discrete value, so this issue shouldn't occur there. It should only occur with continuous targets (targets which model an analog infinite-precision range, e.g. track volume). But usually, rounding issues with continuous targets are not a problem in practice ... it's normal to have very odd numbers.

The OSC target and all other targets that maintain a simulated dummy value (e.g. ReaLearn Dummy target or MIDI send target) are continuous because the dummy value is continuous (= is simply a 64-bit floating point number). The solution in your case is mentioned in my previous comment.
