### ISSUE TITLE
Rounding Bug #2

### ISSUE THREAD

**Issue by JackOrez** [helgoboss/helgobox#1215]
Another Rounding Errror:
https://stash.reaper.fm/49283/Compartment_param.png

Compartment parameter as target has an error when the value reaches 84.0 [83.9999]
The weird thing about this one is, if you set the value slider to say 80.0 before
increasing up to 84.0 using the source, then the value seems to be correct.

**Comment by helgoboss** [comment]
Similar to the "bug 1" issue that you have submitted, this is likely due to the nature of floating point numbers. It's better to not expect floating point numbers to be exact.

With compartment parameters, there's an easy way to avoid such issues: Make them discrete (instead of continuous). Then you will always get integers.

Menu - Compartment parameters - ... - Edit - Value count
