### ISSUE TITLE
Playtime: "Bad state. No element." error

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/helgobox#1368]
See https://github.com/helgoboss/helgobox/discussions/1357#discussioncomment-11574572.

**Comment by Bytheburn** [comment]
Hi Benjamin. Thanks. As I said earlier, on the original thread, given that I've got a slew of complex templates using ReaLearn, would it be safe use ReaPack to uninstall ReaLearn/Playtime then reinstall it again without breaking my templates.

The ReaLearn scripts, which were created at different times with different versions of Realearn, are named differently (see screen shots) but I just tested a few and they all still seem to function correctly...

![image](https://github.com/user-attachments/assets/c45d4a86-289f-4ba0-9ce6-dc4ea0a99e36)
![image](https://github.com/user-attachments/assets/abaf9ff6-f7f0-432c-a350-203e5f981367)

Would it be safe to uninstall Realearn, restart Reaper then reinstall it again via Reapak?

**Comment by Bytheburn** [comment]
Okay. I'll try that. Don't forget that zip was a snapshot before I upated the version. Let me know if you want a fresh zip...

**Comment by Bytheburn** [comment]
Itried that but, as you suggested, it didn't fix anything... :-(

**Comment by helgoboss** [comment]
Patience. Good news is that I was able to reproduce your issue (at least with the old version). I'm confident that I can reproduce it with the new version as well.

**Comment by Bytheburn** [comment]
Brilliant. I await further developments... :-)

**Comment by helgoboss** [comment]
Okay, I found the issue. You probably accidentally hid the matrix by pressing the middle rectangle:

![image](https://github.com/user-attachments/assets/f6190bcb-440f-4c5a-b011-4dd53bb74153)

Press it again to solve the issue.

It's indeed a bug that there's an error message when adding a column while the matrix is hidden, but not a critical one. Will fix it for the next release.

Oh, and by the way. One weird thing about your installation is that some folders are marked as read-only. This is what confuses the Helgobox/Playtime Installer (ReaBoot) ... so I guess that installer never worked for you? Good thing though that we discovered that. I can now adjust the installer and then it should work.

**Comment by Bytheburn** [comment]
Hi Benjamin,

I think you've closed this prematurely (see below)...

Clicking in the boxes at the top right of the window I do indeed now have the matrix back and when I open a new instance I get the option to create a matrix. [cid:0cd139b8-23ec-4e43-9517-bc58b3e454a8]
[cid:9ab8281e-fbac-4dff-bb4c-a4f67a27e347]
I can also confirm the "Bad State: No element" error only occurs when you create a new column when the matrix is hidden.

However, I've still got a serious problem because whenever I close the window and try to reopen it I end up back in a ReaLearn window with no way I can see to restore what I was working on and I've apparently lost all the data I had entered. Clearly this is 100% unusable!

[cid:40a90b02-76bd-4470-8cef-99083f57ea3f]

________________________________

**Comment by Bytheburn** [comment]
Missing screen shots from my mail...
![image](https://github.com/user-attachments/assets/9a8011fb-b60b-4e13-8e45-b19af4332d2c)
![image](https://github.com/user-attachments/assets/368de6f3-b410-4ce7-a982-d4c54c3e7faa)
![image](https://github.com/user-attachments/assets/289d5044-7586-4ff2-a682-e4f0faad165b)

**Comment by Bytheburn** [comment]
Benjamin,
Final comment for tonight. I've found I can restore the window by choosing Show/hide Playtime from Extensions-->Helgoboss--> Playtime menu or by clicking the button installed on the Reaper taskbar, so that's workable. However I think you should definitely be able to do this by selecting it in the FX dialoge of a track as you can with all other VSTs; indeed, as you can with Playtime 1.

That's all for now. I think I can live with this until the next release. Thanks for your prompt attention. I'll let you know If I find any more bugs.

Good night...

**Comment by helgoboss** [comment]
That's possible. You can use Menu => Show app.

I recommend that read: https://docs.helgoboss.org/playtime/usage/prepare.html
