### ISSUE TITLE
Help in configuring FX by name in multiple mappings

### ISSUE THREAD

**Issue by vonglan** [helgoboss/helgobox#252]
When I initially learn mappings for a VST, the VST is selected via "By ID". Then, when I want to save, it is converted automatically to "focused". But when I want to change it to "by name", I need to go into each mapping individually to adapt it (or use an external editor like VIM on the JSON). 
It would be great to have the "save"-popup let me choose between "focused" or "by name + pattern". 
Or the possibility to copy this aspect of one mapping to all other mappings of the currently filtered list.

**Comment by vonglan** [comment]
maybe can be combined somehow with #224 
("go to next mapping and apply same change").

**Comment by helgoboss** [comment]
Not sure if this issue is still relevant after the following planned change: I want to provide a new FX selector "Instance FX" and track selector "Instance track" and a way to set an FX / a track for the whole ReaLearn instance (which can be anything: Focused FX, By name, etc.). Then when saving the preset and discovering something project-dependent, I would always convert the selector to "Instance track / instance FX" instead of "Focused". That should increase reusability of main presets very much and probably render this request unimportant ... or not?

**Comment by vonglan** [comment]
Sorry for not answering this before.
Yes, that would also work.
Slight disadvantage: when "starting from scratch", and loading the Main Mapping preset into the ReaLearn Instance, the "Instance FX" would also need to be chosen (one additional step).
Maybe the preset could also contain a default "Instance FX" (by name pattern, in my case)?
The default "Track FX" would be the current track.

**Comment by helgoboss** [comment]
I just added a menu action to turn make all listed mappings use the unit track / unit FX.

After that, only the unit track / unit FX needs to be changed (and all mappings will follow). Unfortunately, that step is really a bit of manual work because one needs a "helper mapping" to set the unit FX from the GUI. But going the "Unit track / FX" route is the cleanest way, I think. Then you only deal with one track/FX instead with one per mapping (which could be hundreds). I will make a video tutorial about this, soon.

**Comment by helgoboss** [comment]
Ah, BTW. This "turn everything into unit FX" was already available before, but only implicitly when trying to save a preset and having at least one mapping with project-dependent targets. Then it would ask you a question "Make mappings project-independent?" and also make all targets use unit FX (but not the unit track ... it's using numbered tracks there).

**Comment by helgoboss** [comment]
@vonglan I made it more flexible so that your scenario is covered as well:

![image](https://github.com/user-attachments/assets/2d4999c9-66e0-457b-90e7-e571d912c644)
