### ISSUE TITLE
Change question whether to make mappings project-independent to a confirmation

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/helgobox#510]
Reasoning: https://forum.cockos.com/showpost.php?p=2508953&postcount=1845

**Comment by vonglan** [comment]
We had a discussion about this in #353 .
It seems that for different use cases, different addressing defaults for FX parameter targets are useful:
- for ad hoc mappings, created spontaneously and not saved as presets, "by Id" (the current default after "learn") is best, so the relation to the FX is "sticky" when the FX is renamed, moved etc.
- for people using "Auto-load: Depending on focused FX", "focused FX" is perfect
- some folks might prefer "FX by name" as default (e.g. here https://github.com/helgoboss/realearn/issues/188#issuecomment-800926287: "in all my scenario I would always want to control different parameters of different plugins in the chain")

Because "focused" is not the only useful default, I am not sure whether just changing the popup to a confirmation is good. 

Maybe make it dependent on whether "Auto-load" is used for the preset or not? If it is not used, make "FX by name" the default (after confirmation of the popup)?

(#228 is also related , a more complex and more powerful feature.)

**Comment by helgoboss** [comment]
Yes. This deserves some more attention. But I'm not sure how to do it without requiring too much user interaction. It's not possible to automatically detect whether "Auto-load" is going to be used for a preset or not. That's like predicting future :)

**Comment by vonglan** [comment]
Offer a choice of three in the popup? (Keep, Change to "focused FX", Change to "by name"). Or move the whole topic from popup to right-click menu? (Maybe let the popup show a warning that needs to be confirmed once.)

Changing to "focused FX" can always be done (requires less information), changing from "focused FX" to "by name" requires human intelligence.

**Comment by vonglan** [comment]
Just noticed, #252 is also about the same topic.
You suggested Track FX as a solution:

> a new FX selector "Instance FX" and track selector "Instance track" and a way to set an FX / a track for the whole ReaLearn instance (which can be anything: Focused FX, By name, etc.).

**Comment by helgoboss** [comment]
> Or move the whole topic from popup to right-click menu? (Maybe let the popup show a warning that needs to be confirmed once.)

This is a good idea. I implemented it like this in #252.
